### ISSUE TITLE
Banned from Chrome webstore

### ISSUE THREAD

**Issue by Smart123s** [jybp/chrome-youtube-tv#1]
Hi, the extension was banned from the Chrome Web Store. Could you provide any information on why it had happened?

![image](https://user-images.githubusercontent.com/28480228/205428092-0757afb4-15fa-4365-8d88-c14fee231f29.png)

**Comment by brettinternet** [comment]
If this is the same one, looks like it worked until recently when malware was added. https://chrome.google.com/webstore/detail/youtube-for-tv/gmmbpchnelmlmndfnckechknbohhjpge?hl=en-US

**Comment by jybp** [comment]
It's not the same one. I guess Google just decided they didn't want to allow that feature and delisted it. I'm not going to re-publish it.

@Smart123s the only alternative is to manually load the extension with developer mode on with 'Load unpacked' button.
